//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace regression_test_suite.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Internal : global::System.Configuration.ApplicationSettingsBase {
        
        private static Internal defaultInstance = ((Internal)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Internal())));
        
        public static Internal Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RegressionTriggerDateTime {
            get {
                return ((string)(this["RegressionTriggerDateTime"]));
            }
            set {
                this["RegressionTriggerDateTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BackupResultsPath {
            get {
                return ((string)(this["BackupResultsPath"]));
            }
            set {
                this["BackupResultsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RegressionTimeTaken {
            get {
                return ((string)(this["RegressionTimeTaken"]));
            }
            set {
                this["RegressionTimeTaken"] = value;
            }
        }
    }
}
