//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace regression_test_suite.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Regression : global::System.Configuration.ApplicationSettingsBase {
        
        private static Regression defaultInstance = ((Regression)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Regression())));
        
        public static Regression Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\dhiraj_work\\build_installer")]
        public string DFMProInstallerPath {
            get {
                return ((string)(this["DFMProInstallerPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\dhiraj_work\\build_installer")]
        public string CostAddonInstallerPath {
            get {
                return ((string)(this["CostAddonInstallerPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CreoCost_x64.msi")]
        public string CostAddonMSIPackageName {
            get {
                return ((string)(this["CostAddonMSIPackageName"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\installers")]
        public string InstallerCopyPath {
            get {
                return ((string)(this["InstallerCopyPath"]));
            }
            set {
                this["InstallerCopyPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\logs")]
        public string LogFolderPath {
            get {
                return ((string)(this["LogFolderPath"]));
            }
            set {
                this["LogFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\scripts\\Creo3.0")]
        public string ScriptsFolder {
            get {
                return ((string)(this["ScriptsFolder"]));
            }
            set {
                this["ScriptsFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\parts\\creo3.0")]
        public string PartsFolder {
            get {
                return ((string)(this["PartsFolder"]));
            }
            set {
                this["PartsFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\baseline\\creo3.0")]
        public string BaselineFolder {
            get {
                return ((string)(this["BaselineFolder"]));
            }
            set {
                this["BaselineFolder"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DFMProForCreoParametric3_0_x64.msi")]
        public string DFMMSIPackageName {
            get {
                return ((string)(this["DFMMSIPackageName"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\reg")]
        public string RegFilePath {
            get {
                return ((string)(this["RegFilePath"]));
            }
            set {
                this["RegFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\testapp")]
        public string TestAppPath {
            get {
                return ((string)(this["TestAppPath"]));
            }
            set {
                this["TestAppPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\rulefile")]
        public string RuleFilePath {
            get {
                return ((string)(this["RuleFilePath"]));
            }
            set {
                this["RuleFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Geometric\\DFMPro for Creo Parametric(x64)")]
        public string DFMInstallLocation {
            get {
                return ((string)(this["DFMInstallLocation"]));
            }
            set {
                this["DFMInstallLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DFMProETestApplication.exe")]
        public string DFMTestAppName {
            get {
                return ((string)(this["DFMTestAppName"]));
            }
            set {
                this["DFMTestAppName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\DFM_LICENSE\\Geometric_PUN-NITISHG_20170322102937_CPD_123456.lic")]
        public string DFMProLicenseFile {
            get {
                return ((string)(this["DFMProLicenseFile"]));
            }
            set {
                this["DFMProLicenseFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\results_backup")]
        public string TestResultsBackup {
            get {
                return ((string)(this["TestResultsBackup"]));
            }
            set {
                this["TestResultsBackup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\inputcsv\\creo3.0\\Regression_Test_Cases.xlsx")]
        public string RegressionInputFile {
            get {
                return ((string)(this["RegressionInputFile"]));
            }
            set {
                this["RegressionInputFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DFMPro for Creo Parametric(x64)")]
        public string DFMProductName {
            get {
                return ((string)(this["DFMProductName"]));
            }
            set {
                this["DFMProductName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DFMPro for Creo Parametric-Cost add-on")]
        public string CostProductName {
            get {
                return ((string)(this["CostProductName"]));
            }
            set {
                this["CostProductName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\DFM Pro License Server")]
        public string LicenseServerPath {
            get {
                return ((string)(this["LicenseServerPath"]));
            }
            set {
                this["LicenseServerPath"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GSSL DFMPro License Server")]
        public string LicenseServiceName {
            get {
                return ((string)(this["LicenseServiceName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.98.134.26")]
        public string SMTPServer {
            get {
                return ((string)(this["SMTPServer"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public string SMTPPort {
            get {
                return ((string)(this["SMTPPort"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cost.dev@hcl.com")]
        public string EmailFromAddress {
            get {
                return ((string)(this["EmailFromAddress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Jarvis")]
        public string EmailDisplayName {
            get {
                return ((string)(this["EmailDisplayName"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\templates")]
        public string TemplatePath {
            get {
                return ((string)(this["TemplatePath"]));
            }
            set {
                this["TemplatePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\reports")]
        public string ReportPath {
            get {
                return ((string)(this["ReportPath"]));
            }
            set {
                this["ReportPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\pun-nitishg\\creocost")]
        public string SharedPath {
            get {
                return ((string)(this["SharedPath"]));
            }
            set {
                this["SharedPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\dhiraj_work\\tester\\creocost")]
        public string LocalRegPath {
            get {
                return ((string)(this["LocalRegPath"]));
            }
            set {
                this["LocalRegPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SOFTWARE\\MTI Systems\\14")]
        public string MTIRegistryPath {
            get {
                return ((string)(this["MTIRegistryPath"]));
            }
            set {
                this["MTIRegistryPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pun-venus")]
        public string LicenseServer {
            get {
                return ((string)(this["LicenseServer"]));
            }
            set {
                this["LicenseServer"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DFMProForCreoParametric_v5.2_x64_Setup_Creo3.exe")]
        public string DFMInstallerName {
            get {
                return ((string)(this["DFMInstallerName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DFMProforCreo_Cost_add-on_v5.2_x64_Setup_Creo3.exe")]
        public string CostAddonInstallerName {
            get {
                return ((string)(this["CostAddonInstallerName"]));
            }
        }
    }
}
